project:
  type: website
  output-dir: docs

website:
  title: "Invisible Deaths"
  site-url: https://yourusername.github.io/invisible-deaths/
  description: "Exploring gender disparities in death registration in India using Bayesian models and interactive maps."

  navbar:
    background: success
    foreground: light
    search: true
    left:
      - text: "<i class='bi bi-house-door'></i> Home"
        href: index.qmd
      - text: "<i class='bi bi-gear'></i> Methods"
        href: data_methods.qmd
      - text: "<i class='bi bi-bar-chart-line'></i> Results"
        href: results.qmd
      - text: "<i class='bi bi-map'></i> Maps"
        href: completeness.qmd
      - text: "<i class='bi bi-flag'></i> Conclusion"
        href: conclusion.qmd
      - text: "<i class='bi bi-info-circle'></i> About"
        href: about.qmd



format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 2
    smooth-scroll: true
    include-in-header:
      text: |
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
